on:
  pull_request:
    branches:
    - main
    - latest

    paths:
    - 'deployment/prod/Chart.yaml'

jobs:
    check-dependencies:
      name: Check dependency versions
      runs-on: ubuntu-latest

      steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Helm
        run: |
          curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 > get_helm.sh
          chmod 700 get_helm.sh
          ./get_helm.sh

      - name: Check dependency versions
        run: |

          cd deployment/preprod
          PREPROD=cat Chart.yaml | yq '.dependencies[] | select(.name=="dos") | .version'
          #PREPROD=$(helm dependency list | tail -n +2 | awk '{print $2}')
          echo "PREPROD: $PREPROD"

          cd ../..
          cd deployment/prod
          echo "In prod"
          PROD=cat Chart.yaml | yq '.dependencies[] | select(.name=="dos") | .version'
          #PROD=$(helm dependency list | tail -n +2 | awk '{print $2}')
          echo "PROD: $PROD"

          if [ "$PREPROD" != "$PROD" ]; then exit 1; fi