on:
  pull_request:
    branches:
    - main
    - latest

    paths:
    - 'deployment/prod/Chart.yaml'

jobs:
    check-dependencies:
      name: Check dependency versions
      runs-on: ubuntu-latest

      steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Helm
        run: |
          curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 > get_helm.sh
          chmod 700 get_helm.sh
          ./get_helm.sh
      - run: |
          ls -ld deployment/preprod
          ls -ld deployment/prod
          ls -l deployment

      - name: Check dependency versions
        run: |

          cd deployment/preprod
          echo "In preprod"
          #PREPROD=$(helm dependency list -o json | jq -r '.[0].version')
          PREPROD=$(helm dependency list | tail -n +2 | awk '{print $2}')
          echo "PREPROD: $PREPROD"

          cd ../..
          cd deployment/prod
          echo "In prod"
          #PROD=$(helm dependency list -o json | jq -r '.[0].version')
          PROD=$(helm dependency list | tail -n +2 | awk '{print $2}')
          echo "PROD: $PROD"

          if [ "$PREPROD" != "$PROD" ]; then exit 1; fi