on:
  pull_request:
    branches:
    - main
    - test

    paths:
    - 'deployment/cfx/prod/dos/Chart.yaml'

jobs:
    check-dependencies:
      name: Check dependency versions
      runs-on: ubuntu-latest

      steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Helm
        run: |
          curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 > get_helm.sh
          chmod 700 get_helm.sh
          ./get_helm.sh

      - name: Check dependency versions
        run: |
          cd deployment/cfx/preprod/dos

          PREPROD=$(helm dependency list -o json | jq -r '.[0].version')
          echo "Ahtasham"
          echo "PREPROD: $PREPROD"

      - run: |
          echo "Ahtasham2"
          ls -ld deployment/cfx/prod/dos

          cd deployment/cfx/prod/dos
          PROD=$(helm dependency list -o json | jq -r '.[0].version')
          echo "PROD: $PROD"

          if [ "$PREPROD" != "$PROD" ]; then exit 1; fi